### PR TITLE
Add new sites

### PR DESCRIPTION
**Pull request by tamas646**
Adding several new sites based on my own research and @Pkhrl [suggestion](https://github.com/4skinSkywalker/Anti-Porn-HOSTS-File/issues/64#issuecomment-1470028330).

### CODE REVIEW

**Comment by 4skinSkywalker** [comment]
Hi, may I ask you if you added the www prefixed sites?
In case you didn't just tell me and I'll make sure to introduce those.

**Comment by tamas646** [comment]
@4skinSkywalker Hi, no I did not. Next time I will add those too. :)

**Comment by tamas646** [comment]
I added some new sites. (now included the www. versions too :))

**Comment by tamas646** [comment]
Closing to support the [new pull request](https://github.com/4skinSkywalker/Anti-Porn-HOSTS-File/pull/84) made by @badlydrawnface.
Thanks for the work :wink:

**Pull request closed without merging**
